services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    # container_name: streamlit_frontend
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network
    develop:
      watch:
          - action: sync
            path: ./front
            target: /app
            ignore:
              - __pycache__/
              - .git/
          - action: rebuild
            path: ./front/requirements.txt

  api:
    build: ./api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
    develop:
      watch: 
          - action: sync
            path: ./api
            target: /code
            ignore:
              - __pycache__/
              - .git/
          - action: rebuild
            path: .api/requirements.txt

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge