services:
  frontend:
    build: ./front
    container_name: streamlit_frontend
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./api
    container_name: fastapi_api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis_db
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge